export const values = {
  detail: {
    mainTitle: "event Detail",
    imageUpload: {
      label: "Cover Image",
      rules: [{ required: true, message: "upload your event image" }],
    },
    blockChain: {
      name: "blockchainId",
      label: "BlockChain",
      inputType: "string",
      rules: [
        { required: true, message: "select your event nft type" }],
      placeholder: "select your event nft type",
      options: [
        { value: 1, title: "ETHEREUM" },
        { value: 3, title: "POLYGON" },
        { value: 4, title: "SOLANA" },
        { value: 5, title: "BSC" },
        { value: 11, title: "FLOW" },
        { value: 33, title: "CARDANO" },
        { value: 34, title: "AVALANCHE" },
        { value: 8, title: "WAX" },
        { value: 32, title: "HARMONY" },
        { value: 9, title: "ELROND" },
        { value: 16, title: "IMMUTABLE X" },
        { value: 35, title: "OTHER" }
      ],
    },
    marketPlace: {
      name: "marketplaceId",
      label: "market place",
      inputType: "select",
      rules: [{ required: true, message: "select your market place" }],
      placeholder: "select your market place",
      options: [
        { value: 1, title: "OpenSea" },
        { value: 3, title: "magicEden" },
        { value: 5, title: "Rarible" },
        { value: 6, title: "Solsea" },
        { value: 7, title: "MakersPlace" },
        { value: 8, title: "Crypto.com" },
        { value: 9, title: "Solanart" },
        { value: 10, title: "Foundation" },
        { value: 11, title: "Mintable" },
        { value: 12, title: "NiftyGateway" },

      ],
    },
    category: {
      name: "category",
      label: "category",
      inputType: "category",
      rules: [{ required: true, message: "select Category" }],
      placeholder: "select Tags",
      options: [
        { value: "art", title: "art" },
        { value: "auction", title: "auction" },
        { value: "charity", title: "charity" },
        { value: "dao", title: "dao" },
        { value: "defi", title: "defi" },
        { value: "game", title: "game" },
        { value: "giveaway", title: "giveaway" },
        { value: "music", title: "music" },
        { value: "rewards", title: "rewards" },
        { value: "sports", title: "sports" },
      ],
    },
    tags: {
      name: "tags",
      label: "tags",
      inputType: "tags",
      rules: [{ required: true, message: "select tags" }],
      placeholder: "select Tags",
      options: [
        { value: "art", title: "art" },
        { value: "auction", title: "auction" },
        { value: "charity", title: "charity" },
        { value: "dao", title: "dao" },
        { value: "defi", title: "defi" },
        { value: "game", title: "game" },
        { value: "giveaway", title: "giveaway" },
        { value: "music", title: "music" },
        { value: "rewards", title: "rewards" },
        { value: "sports", title: "sports" },
      ],
    },
    price: {
      name: "mintingPrice",
      label: "Minting price",
      inputType: "number",
      rules: [{ required: true, message: "write price" }],
      placeholder: "0.015",
    },
    amount: {
      name: "numberOfMinting",
      label: "Minting amount",
      inputType: "number",
      rules: [{ required: true, message: "minting amount" }],
      placeholder: "1,000",
    },
  },
};


      // { value: 12, title: "Fantom" },
        // { value: 13, title: "EOSIO" },
        // { value: 14, title: "Terra" },
        // { value: 15, title: "Internet Computer" },
        // { value: 17, title: "XRP Ledger" },
        // { value: 18, title: "Secret" },
        // { value: 19, title: "Moonriver" },
        // { value: 20, title: "VeChain" },
        // { value: 21, title: "xDAI" },
        // { value: 22, title: "NEAR" },
        // { value: 23, title: "Theta" },
        // { value: 24, title: "Hathor" },
        // { value: 25, title: "Waves" },
        // { value: 26, title: "DeSo" },
        // { value: 27, title: "HIVE" },
        // { value: 28, title: "Ethernity" },
        // { value: 29, title: "TRON" },
        // { value: 30, title: "Stellar XLM" },
        // { value: 31, title: "LINE" },
         // { value: 6, title: "Avax NetWork" },
        // { value: 7, title: "Cronos" },
        // { value: 10, title: "Tezos" },